---



    - name: "{{var_pool|upper}}: Copy Cleanup script"
      template:
        src: clean.sh.j2
        dest: "/opt/clean_{{var_pool}}.sh"
        owner: root
        group: root
        mode: "700"
      become: yes
      become_user: root
