---



    - name: "{{var_pool|upper}}: Create folders"
      file:
        path: "{{item.PATH}}"
        mode: "{{item.MODE}}"
        owner: "{{item.OWNER}}"
        group: "{{item.GROUP}}"
        state: directory
      become: yes
      become_user: root
      with_items:
        - "{{var_folders}}" 
