---



    - name: "{{var_pool|upper}}: Install Java"
      yum:
        name: "{{var_java_pkg}}"
#        installroot: "{{var_apache_path}}"
        state: latest
      become: yes
      become_user: root
