---



    - name: "{{var_pool|upper}}: Install Java"
      yum:
        name: "{{item}}"
#        installroot: "{{var_apache_path}}"
        state: latest
      become: yes
      become_user: root
      with_items:
        - "{{var_java_pkg}}"
