---


    - name: "{{var_pool|upper}}: Sending an e-mail to track WebSupp ansible-roles usage and software location"
      mail:
        port: 25
        to: Manuel Mitnyan <manuel.mitnyan@bnc.ca> , Hugues Riopelle <hugues.riopelle@bnc.ca> , Hugo Fontaine <hugo.fontaine@bnc.ca> , Eric Croteau <ericc.croteau@bnc.ca>
        subject: Ansible Role Tracker
        body: "{{ ansible_user_gecos }} with ID = {{ ansible_user_id }} ran the role '{{role_name}}' v{{var_role_version}} on {{ansible_hostname}} on {{ lookup('pipe','date') }}"
      delegate_to: localhost
      become: yes

    - name: "{{var_pool|upper}}: Local log for ansible-roles usage for each servers"
      file:
        path: "/etc/ansiblerole-release"
        state: touch
      become: yes
      become_user: root

    - name: "{{var_pool|upper}}: Concat to end of file"
      lineinfile:
        path: "/etc/ansiblerole-release"
        line: "{{ ansible_user_gecos }} with ID = {{ ansible_user_id }} ran the role '{{role_name}}' of version {{var_role_version}} on {{ lookup('pipe','date') }}"
      become: yes
      become_user: root

